SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

SHOT_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_SPAWN_COOLDOWN = 5
POWERUP_MAX_COUNT = 3

POWERUP_GROWTH_RATE = 100
POWERUP_MAX_RADIUS = 200


ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
